spring:
  application:
    name: 'application-consumer'
  profiles:
    active: dev
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        server-addr: nacos.didispace.com
        #namespace: d2ca62d0-2fcb-4155-b38e-30f6f908caf1
  resources:
    cache:
      cachecontrol:
        cache-private: true
        max-age: 3600

app:
  id: ${spring.application.name}
apollo:
  cache-dir: 'D:\TeamWork\arthas-all\spring-boot-web-test\src\main\resources\tests'
  autoUpdateInjectedSpringProperties: true
  access-key:
    secret: d7e98dedace8409fca9c956b29cda4b579681f33f54e1ea77ec5589c28419001
  bootstrap:
    enabled: true
    namespaces: application, business, auth.yml, test1.yml, test2.yml, test3.yml, test4.yml, test5.yml, test6.yml, test7.yml, test8.yml, test9.yml, test10.yml, test11.yml, test12.yml, test13.yml
    eagerLoad:
      enabled: true

# logging path
logging:
  config: classpath:logback.xml
  file:
    path: './logs'


server:
  port: 8995
